export const JOB_ROLES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Researcher",
  "DevOps Engineer",
  "Cloud Architect",
  "System Administrator",
  "Network Engineer",
  "Database Administrator",
  "Cybersecurity Analyst",
  "Security Engineer",
  "QA Engineer",
  "Test Automation Engineer",
  "Product Manager",
  "Project Manager",
  "Scrum Master",
  "Business Analyst",
  "UX Designer",
  "UI Designer",
  "Graphic Designer",
  "Product Designer",
  "Marketing Manager",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Content Marketing Manager",
  "Social Media Manager",
  "Sales Manager",
  "Account Executive",
  "Business Development Representative",
  "Customer Success Manager",
  "Technical Support Specialist",
  "Help Desk Technician",
  "IT Manager",
  "Chief Technology Officer (CTO)",
  "Chief Information Officer (CIO)",
  "Human Resources Manager",
  "Talent Acquisition Specialist",
  "Technical Recruiter",
  "HR Generalist",
  "Financial Analyst",
  "Accountant",
  "Auditor",
  "Chief Financial Officer (CFO)",
  "Operations Manager",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Manufacturing Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Biomedical Engineer",
  "Industrial Engineer",
  "Aerospace Engineer",
  "Environmental Engineer",
  "Architect",
  "Interior Designer",
  "Urban Planner",
  "Legal Counsel",
  "Corporate Lawyer",
  "Paralegal",
  "Compliance Officer",
  "Public Relations Manager",
  "Corporate Communications Specialist",
  "Event Manager",
  "Copywriter",
  "Technical Writer",
  "Translator / Interpreter",
  "Journalist",
  "Editor",
  "Video Editor",
  "Animator",
  "Game Developer",
  "Audio Engineer",
  "Photographer",
  "Videographer",
  "Teacher / Educator",
  "Professor",
  "Instructional Designer",
  "E-learning Developer",
  "Research Scientist",
  "Laboratory Technician",
  "Pharmacist",
  "Registered Nurse",
  "Physician / Doctor",
  "Dentist",
  "Physical Therapist",
  "Medical Billing Specialist",
  "Healthcare Administrator",
  "Retail Manager",
  "Store Supervisor",
  "Merchandiser",
  "Real Estate Agent",
  "Property Manager",
  "Chef / Head Cook",
  "Restaurant Manager",
  "Hotel Manager",
  "Travel Consultant",
  "Flight Attendant",
  "Pilot",
  "Fitness Instructor",
  "Personal Trainer"
];
